spring:
  datasource:
    username: sa
    password:
    #url: jdbc:h2:mem:querydsl
    url: jdbc:log4jdbc:h2:mem:querydsl
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
        default_batch_fetch_size: 100
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace